# PLEASE DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING :)

# This template is based on commit:
#  https://gitlab.gbar.dtu.dk/latex/dtutemplates/commit/f8481c69807365fd899381fd21c657967c433c22

# Ensure external/ is in the path
$ENV{'TEXINPUTS'}='./external//:' . $ENV{'TEXINPUTS'}; 

